const madHatterPhrases = {
	tea: [
		`that's my cup of tea!`,
		`clean cup! clean cup! move DOOOOWN!`,
		`CHANGE PLACES!`,
	],
	mad: [
		`we're all MAD here`,
		`you must be mad or you wouldn't have come here`,
		`you might just as well say that 'I see what I eat' is the same as 'I eat what I see'`,
		'two days wrong!',
	],
	down: [
		'only up here!',
		'bear market? you mean build market?',
		'crypto is a wonderland; anything is possible!',
		'we are here fam',
	],
	poap: [
		'you get a POAP. and you get a POAP. everyone gets a POAP! where are the POAPs?',
		'The more events you attend, the higher the chance of a POAP!',
	],
	app: [
		'DEV GUILD STRONK 💪',
		'gm',
		'Hello ser, would you like to hear about our lord and savior Vitalik...',
		'The story of Ethereum goes like this... Once upon a time there was a little known player playing World of Warcraft...',
		'Hello fren! Make sure you never share your seed phrase :)',
		'I am not available at the moment... Please leave a message at the sound of the beep ... BEEP.',
		'Did you see the gas fees today? You don\'t want to know...',
		'Hello 👋',
		'Howdy!',
		'Hey!',
		'Go Bankless!',
		'Nice to meet you!',
		'It\'s great to see you!',
		'Ahoy!',
		'BANKLESSDAO STRONK 💪',
		'ALL GUILDS STRONK 💪',
		'wagmi',
		'The future is DAO.',
		'why is a raven like a writing desk?',
		'TO THE MOOOOOON!',
		'I am a complete degenerate.',
		'👀',
		'Hello! I\'m so glad you are here! wagmi!',
		`did someone say ... GOVERNANCE? i'm titillating with excitement!`,
		'not all heroes wear capes!',
	],
};

export default madHatterPhrases;
