name: Deploy to Production Environment
on:
  push:
    branches:
      - 'main'
jobs:
  deploy-prod:
    environment:
      name: production
      url: https://app.logdna.com/273e532689/logs/view?apps=mad-hatter-bdao
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.12.1'
      - name: Install dependencies
        run: yarn install
      - name: Lint Code
        run: yarn lint
      - name: Build and Compile Typescript
        run: yarn build
      - name: Run test cases
        run: yarn test --watchAll=false
      - name: Deploy to Heroku Shared Test Environment
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.PROD_HEROKU_API_KEY}}
          heroku_app_name: 'mad-hatter-bdao'
          heroku_email: 'joshua@nonsensecodes.io'
          procfile: 'worker: yarn prod'
        env:
          HD_DISCORD_BOT_TOKEN: ${{secrets.PROD_DISCORD_TOKEN}}
          HD_DISCORD_BOT_PUBLIC_KEY: ${{secrets.PROD_BOT_PUBLIC_KEY}}
          HD_DISCORD_BOT_APPLICATION_ID: ${{secrets.PROD_BOT_APPLICATION_ID}}
          HD_DISCORD_OWNER_ID: ${{secrets.PROD_DISCORD_OWNER_ID}}
          HD_MONGODB_USERNAME: ${{secrets.PROD_MONGODB_USERNAME}}
          HD_MONGODB_PASS: ${{secrets.PROD_MONGODB_PASS}}
          HD_MONGODB_CLUSTER: ${{secrets.PROD_MONGODB_CLUSTER}}
          HD_NOTION_TOKEN: ${{secrets.PROD_NOTION_TOKEN}}
          HD_LOKI_HOST: ${{secrets.PROD_LOKI_HOST}}
          HD_LOKI_USERNAME: ${{secrets.PROD_LOKI_USERNAME}}
          HD_LOKI_PASSWORD: ${{secrets.PROD_LOKI_PASSWORD}}
          HD_SENTRY_IO_DSN: ${{secrets.PROD_SENTRY_IO_DSN}}
